name: Cypress Tests

on: [push]

jobs:
  Run-Cypress-Tests:
    runs-on: ubuntu-latest
    env:
      CYPRESS_API_URL={{ secrets.CYPRESS_API_URL }}
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Run Tests
        run: npx cy2 run --parallel --record --key somekey --ci-build-id `Build ${{ GITHUB_RUN_ID }}`

